In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [3]:

df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [4]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [5]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [6]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

Normalisation in DL

In [7]:
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [8]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=42, stratify=y)

### In simple words

> `stratify=y` ensures that the **class distribution of `y` remains approximately the same** in both the training and testing datasets.

### Why is it important?

It is particularly useful when the dataset is **imbalanced**.

For example, if:

```text
Class 0 → 95%
Class 1 → 5%
```

we want both training and testing datasets to contain roughly:

```text
Class 0 → 95%
Class 1 → 5%
```

This helps the model get a representative training set and makes the test set a better representation of the original data.

### Key Point

```python
stratify=y
```

means:

**"Split the data while preserving the class proportions present in `y`."**

In [10]:
model = keras.Sequential([
    layers.Input(shape= (X_train.shape[1],)),
    layers.Dense(8, activation='relu'), # hidden layer - layers.Dense(power of 2, activation='relu'),
    layers.Dense(1, activation='sigmoid'), # output layer -
])

## **Neural Network Model**

```python
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),

    layers.Dense(8, activation='relu'),  # Hidden layer

    layers.Dense(1, activation='sigmoid'),  # Output layer
])
```

### Brief Explanation

* **`keras.Sequential`** → Creates a neural network where layers are arranged **one after another**.
* **`Input(shape=(X_train.shape[1],))`** → Defines the number of **input features**.
* **`Dense(8, activation='relu')`** → Hidden layer with **8 neurons** using the **ReLU** activation function.
* **`Dense(1, activation='sigmoid')`** → Output layer with **1 neuron** using **Sigmoid**, which gives a probability between **0 and 1**.

### Architecture

```text
Input Features
      ↓
8 Neurons (ReLU)
      ↓
1 Neuron (Sigmoid)
      ↓
Prediction
```

> **Note:** `8` is the number of neurons in the hidden layer. It is a design choice and can be changed depending on the problem.

In [11]:
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

## `model.compile()`

```python
model.compile(
    optimizer='sgd',
    loss='binary_crossentropy',
    metrics=['accuracy']
)
```

`model.compile()` **configures the neural network before training**. It tells the model **how to learn and how to measure its performance**.

### 1. `optimizer='sgd'`

**SGD = Stochastic Gradient Descent**

* Decides **how the model updates its weights**.
* Uses the **gradient of the loss** to move weights in a direction that reduces the error.

```text
Prediction
    ↓
Calculate Loss
    ↓
Calculate Gradients
    ↓
SGD updates weights
    ↓
Better Prediction
```

### 2. `loss='binary_crossentropy'`

The **loss function** measures how wrong the model's predictions are.

`binary_crossentropy` is used for **binary classification**, where there are two classes:

```text
0 → Negative
1 → Positive
```

It works well with the `sigmoid` activation in the output layer.

```python
layers.Dense(1, activation='sigmoid')
```

The sigmoid produces a probability between **0 and 1**, and binary cross-entropy measures how close that probability is to the actual label.

### 3. `metrics=['accuracy']`

`accuracy` tells Keras to **calculate the percentage of correct predictions** during training and testing.

For example:

```text
100 predictions
80 correct
↓
Accuracy = 80%
```

### In short

| Parameter                    | Purpose                        |
| ---------------------------- | ------------------------------ |
| `optimizer='sgd'`            | **How to update weights**      |
| `loss='binary_crossentropy'` | **How to calculate error**     |
| `metrics=['accuracy']`       | **How to measure performance** |

### Simple way to remember

> **Optimizer → How to learn**
> **Loss → How wrong are we?**
> **Metric → How well are we doing?**

In [15]:
history_full = model.fit(X_train, y_train, epochs=100, batch_size=len(X_train), verbose=1) # send all at one time

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 1.0000 - loss: 0.5570
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 1.0000 - loss: 0.5567
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5564
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 1.0000 - loss: 0.5561
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 0.5558
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 1.0000 - loss: 0.5555
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.5552
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5549
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 1.0000 - loss: 0.5546
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5543
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5540
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 1.0000 - loss: 0.5537
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 1.0000 - loss: 0.5534
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 1.0000 - loss: 0.5531
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.5528
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.5525
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 1.0000 - loss: 0.5522
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.5519
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.5516
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.5514
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 1.0000 - loss: 0.5511
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 1.0000 - loss: 0.5508
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 1.0000 - loss: 0.5505
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 0.5502
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5499
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5496
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5493
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 1.0000 - loss: 0.5490
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5487
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 1.0000 - loss: 0.5484
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 1.0000 - loss: 0.5481
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5478
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.5475
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 1.0000 - loss: 0.5472
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.5469
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5466
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5463
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 1.0000 - loss: 0.5461
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5458
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5455
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 1.0000 - loss: 0.5452
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 1.0000 - loss: 0.5449
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.5446
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 1.0000 - loss: 0.5443
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 1.0000 - loss: 0.5440
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step - accuracy: 1.0000 - loss: 0.5437
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 296ms/step - accuracy: 1.0000 - loss: 0.5434
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - accuracy: 1.0000 - loss: 0.5431
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - accuracy: 1.0000 - loss: 0.5428
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 1.0000 - loss: 0.5425
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 1.0000 - loss: 0.5422
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 1.0000 - loss: 0.5419
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 1.0000 - loss: 0.5417
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step - accuracy: 1.0000 - loss: 0.5414
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - accuracy: 1.0000 - loss: 0.5411
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - accuracy: 1.0000 - loss: 0.5408
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 1.0000 - loss: 0.5405
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 1.0000 - loss: 0.5402
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 1.0000 - loss: 0.5399
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - accuracy: 1.0000 - loss: 0.5396
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 1.0000 - loss: 0.5393
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 1.0000 - loss: 0.5390
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - accuracy: 1.0000 - loss: 0.5387
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 1.0000 - loss: 0.5384
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 1.0000 - loss: 0.5382
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - accuracy: 1.0000 - loss: 0.5379
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.5376
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 1.0000 - loss: 0.5373
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 1.0000 - loss: 0.5370
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 1.0000 - loss: 0.5367
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - accuracy: 1.0000 - loss: 0.5364
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - accuracy: 1.0000 - loss: 0.5361
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 188ms/step - accuracy: 1.0000 - loss: 0.5358
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 1.0000 - loss: 0.5355
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 1.0000 - loss: 0.5352
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 1.0000 - loss: 0.5350
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 1.0000 - loss: 0.5347
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 1.0000 - loss: 0.5344
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 1.0000 - loss: 0.5341
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 1.0000 - loss: 0.5338
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - accuracy: 1.0000 - loss: 0.5335
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 273ms/step - accuracy: 1.0000 - loss: 0.5332
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 1.0000 - loss: 0.5329
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - accuracy: 1.0000 - loss: 0.5326
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 1.0000 - loss: 0.5324
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - accuracy: 1.0000 - loss: 0.5321
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 1.0000 - loss: 0.5318
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.9167 - loss: 0.5315
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.9167 - loss: 0.5312
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.9167 - loss: 0.5309
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9167 - loss: 0.5306
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9167 - loss: 0.5303
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.9167 - loss: 0.5300
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.9167 - loss: 0.5298
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.9167 - loss: 0.5295
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.9167 - loss: 0.5292
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 0.9167 - loss: 0.5289
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.9167 - loss: 0.5287
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.9167 - loss: 0.5284
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - accuracy: 0.9167 - loss: 0.5281

In [17]:
X_train_np = np.asarray(X_train, dtype=np.float32)
X_test_np  = np.asarray(X_test, dtype=np.float32)

y_train_np = np.asarray(y_train, dtype=np.float32)
y_test_np  = np.asarray(y_test, dtype=np.float32)

history = model.fit(
    X_train_np,
    y_train_np,
    validation_data=(X_test_np, y_test_np),
    epochs=100,
    batch_size=1, # one at a time
    verbose=1
)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 1.0000 - loss: 0.4528 - val_accuracy: 1.0000 - val_loss: 0.4869
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4503 - val_accuracy: 1.0000 - val_loss: 0.4844
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4477 - val_accuracy: 1.0000 - val_loss: 0.4809
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.4449 - val_accuracy: 1.0000 - val_loss: 0.4781
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4421 - val_accuracy: 1.0000 - val_loss: 0.4752
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4393 - val_accuracy: 1.0000 - val_loss: 0.4724
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4366 - val_accuracy: 1.0000 - val_loss: 0.4691
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4339 - val_accuracy: 1.0000 - val_loss: 0.4660
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4312 - val_accuracy: 1.0000 - val_loss: 0.4630
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4286 - val_accuracy: 1.0000 - val_loss: 0.4601
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4259 - val_accuracy: 1.0000 - val_loss: 0.4570
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.4232 - val_accuracy: 1.0000 - val_loss: 0.4540
Epoch 13/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4206 - val_accuracy: 1.0000 - val_loss: 0.4512
Epoch 14/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4179 - val_accuracy: 1.0000 - val_loss: 0.4487
Epoch 15/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4153 - val_accuracy: 1.0000 - val_loss: 0.4456
Epoch 16/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4129 - val_accuracy: 1.0000 - val_loss: 0.4425
Epoch 17/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4103 - val_accuracy: 1.0000 - val_loss: 0.4394
Epoch 18/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4079 - val_accuracy: 1.0000 - val_loss: 0.4368
Epoch 19/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4052 - val_accuracy: 1.0000 - val_loss: 0.4344
Epoch 20/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4029 - val_accuracy: 1.0000 - val_loss: 0.4318
Epoch 21/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4006 - val_accuracy: 1.0000 - val_loss: 0.4289
Epoch 22/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.3981 - val_accuracy: 1.0000 - val_loss: 0.4264
Epoch 23/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3951 - val_accuracy: 1.0000 - val_loss: 0.4227
Epoch 24/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.3934 - val_accuracy: 1.0000 - val_loss: 0.4200
Epoch 25/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3909 - val_accuracy: 1.0000 - val_loss: 0.4174
Epoch 26/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3886 - val_accuracy: 1.0000 - val_loss: 0.4153
Epoch 27/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.3864 - val_accuracy: 1.0000 - val_loss: 0.4125
Epoch 28/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3841 - val_accuracy: 1.0000 - val_loss: 0.4097
Epoch 29/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.3818 - val_accuracy: 1.0000 - val_loss: 0.4074
Epoch 30/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3793 - val_accuracy: 1.0000 - val_loss: 0.4042
Epoch 31/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3772 - val_accuracy: 1.0000 - val_loss: 0.4023
Epoch 32/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3752 - val_accuracy: 1.0000 - val_loss: 0.3996
Epoch 33/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3724 - val_accuracy: 1.0000 - val_loss: 0.3980
Epoch 34/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3704 - val_accuracy: 1.0000 - val_loss: 0.3960
Epoch 35/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3683 - val_accuracy: 1.0000 - val_loss: 0.3924
Epoch 36/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3666 - val_accuracy: 1.0000 - val_loss: 0.3900
Epoch 37/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.3645 - val_accuracy: 1.0000 - val_loss: 0.3874
Epoch 38/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3624 - val_accuracy: 1.0000 - val_loss: 0.3852
Epoch 39/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3604 - val_accuracy: 1.0000 - val_loss: 0.3829
Epoch 40/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3584 - val_accuracy: 1.0000 - val_loss: 0.3809
Epoch 41/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3554 - val_accuracy: 1.0000 - val_loss: 0.3775
Epoch 42/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3544 - val_accuracy: 1.0000 - val_loss: 0.3753
Epoch 43/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3525 - val_accuracy: 1.0000 - val_loss: 0.3731
Epoch 44/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3501 - val_accuracy: 1.0000 - val_loss: 0.3711
Epoch 45/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3485 - val_accuracy: 1.0000 - val_loss: 0.3690
Epoch 46/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.3462 - val_accuracy: 1.0000 - val_loss: 0.3678
Epoch 47/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3443 - val_accuracy: 1.0000 - val_loss: 0.3645
Epoch 48/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3425 - val_accuracy: 1.0000 - val_loss: 0.3632
Epoch 49/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3405 - val_accuracy: 1.0000 - val_loss: 0.3599
Epoch 50/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.3391 - val_accuracy: 1.0000 - val_loss: 0.3576
Epoch 51/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3373 - val_accuracy: 1.0000 - val_loss: 0.3555
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.3356 - val_accuracy: 1.0000 - val_loss: 0.3541
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3337 - val_accuracy: 1.0000 - val_loss: 0.3515
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.3318 - val_accuracy: 1.0000 - val_loss: 0.3489
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.3303 - val_accuracy: 1.0000 - val_loss: 0.3471
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9167 - loss: 0.3284 - val_accuracy: 1.0000 - val_loss: 0.3463
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9167 - loss: 0.3266 - val_accuracy: 1.0000 - val_loss: 0.3454
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.3252 - val_accuracy: 1.0000 - val_loss: 0.3430
Epoch 59/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 1.0000 - loss: 0.3235 - val_accuracy: 1.0000 - val_loss: 0.3409
Epoch 60/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.3220 - val_accuracy: 1.0000 - val_loss: 0.3385
Epoch 61/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 1.0000 - loss: 0.3201 - val_accuracy: 1.0000 - val_loss: 0.3370
Epoch 62/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 1.0000 - loss: 0.3185 - val_accuracy: 1.0000 - val_loss: 0.3343
Epoch 63/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.3165 - val_accuracy: 1.0000 - val_loss: 0.3316
Epoch 64/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.3154 - val_accuracy: 1.0000 - val_loss: 0.3307
Epoch 65/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 1.0000 - loss: 0.3137 - val_accuracy: 1.0000 - val_loss: 0.3298
Epoch 66/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.3123 - val_accuracy: 1.0000 - val_loss: 0.3279
Epoch 67/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.3105 - val_accuracy: 1.0000 - val_loss: 0.3266
Epoch 68/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.3092 - val_accuracy: 1.0000 - val_loss: 0.3249
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 1.0000 - loss: 0.3076 - val_accuracy: 1.0000 - val_loss: 0.3230
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 1.0000 - loss: 0.3059 - val_accuracy: 1.0000 - val_loss: 0.3203
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 1.0000 - loss: 0.3047 - val_accuracy: 1.0000 - val_loss: 0.3186
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 1.0000 - loss: 0.3027 - val_accuracy: 1.0000 - val_loss: 0.3184
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.3017 - val_accuracy: 1.0000 - val_loss: 0.3169
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 0.3000 - val_accuracy: 1.0000 - val_loss: 0.3139
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.2989 - val_accuracy: 1.0000 - val_loss: 0.3129
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 1.0000 - loss: 0.2974 - val_accuracy: 1.0000 - val_loss: 0.3114
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2952 - val_accuracy: 1.0000 - val_loss: 0.3082
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2947 - val_accuracy: 1.0000 - val_loss: 0.3065
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.2932 - val_accuracy: 1.0000 - val_loss: 0.3059
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2917 - val_accuracy: 1.0000 - val_loss: 0.3039
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.2896 - val_accuracy: 1.0000 - val_loss: 0.3045
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2890 - val_accuracy: 1.0000 - val_loss: 0.3020
Epoch 83/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2868 - val_accuracy: 1.0000 - val_loss: 0.3025
Epoch 84/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2867 - val_accuracy: 1.0000 - val_loss: 0.3004
Epoch 85/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2851 - val_accuracy: 1.0000 - val_loss: 0.2992
Epoch 86/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2834 - val_accuracy: 1.0000 - val_loss: 0.2988
Epoch 87/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2828 - val_accuracy: 1.0000 - val_loss: 0.2967
Epoch 88/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2810 - val_accuracy: 1.0000 - val_loss: 0.2959
Epoch 89/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2801 - val_accuracy: 1.0000 - val_loss: 0.2947
Epoch 90/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2788 - val_accuracy: 1.0000 - val_loss: 0.2922
Epoch 91/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2773 - val_accuracy: 1.0000 - val_loss: 0.2917
Epoch 92/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2757 - val_accuracy: 1.0000 - val_loss: 0.2916
Epoch 93/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2749 - val_accuracy: 1.0000 - val_loss: 0.2884
Epoch 94/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2735 - val_accuracy: 1.0000 - val_loss: 0.2884
Epoch 95/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2723 - val_accuracy: 1.0000 - val_loss: 0.2850
Epoch 96/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2709 - val_accuracy: 1.0000 - val_loss: 0.2821
Epoch 97/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2696 - val_accuracy: 1.0000 - val_loss: 0.2832
Epoch 98/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2691 - val_accuracy: 1.0000 - val_loss: 0.2822
Epoch 99/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2678 - val_accuracy: 1.0000 - val_loss: 0.2817
Epoch 100/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2670 - val_accuracy: 1.0000 - val_loss: 0.2799

## Converting Data and Training the Model

### Code

X_train_np = np.asarray(X_train, dtype=np.float32)
X_test_np  = np.asarray(X_test, dtype=np.float32)

y_train_np = np.asarray(y_train, dtype=np.float32)
y_test_np  = np.asarray(y_test, dtype=np.float32)

history = model.fit(
    X_train_np,
    y_train_np,
    validation_data=(X_test_np, y_test_np),
    epochs=100,
    batch_size=4,
    verbose=1
)

### Explanation

- **`np.asarray()`** → Converts the data into NumPy arrays.
- **`dtype=np.float32`** → Converts values to `float32` for TensorFlow/Keras.
- **`X_train_np, y_train_np`** → Training features and labels.
- **`validation_data`** → Evaluates the model using test data.
- **`epochs=100`** → Trains the model 100 times on the complete training data.
- **`batch_size=4`** → Processes 4 samples at a time before updating weights (if there are 10 rows then send them all instead of sending a single row).
- **`verbose=1`** → Displays training progress.
- **`history`** → Stores training and validation loss/accuracy.

### In Short

**Convert data → Train → Validate → Repeat 100 times → Store results**

## Cost Function vs Mean Squared Error (MSE)

### What is a Cost Function?

A **cost function** measures how wrong the model's predictions are compared to the actual values.

It gives us a single number representing the **overall error** of the model.

> **Goal of training:** Minimize the cost function so that the model's predictions become better.

### Example

Suppose the actual values are:

Actual: `[10, 20, 30]`

Predicted: `[12, 18, 35]`

The cost function calculates how different the predictions are from the actual values.

Loss function — error for a single training example

Cost function — error averaged/summed over the entire dataset (or a batch)

---

## What is Mean Squared Error (MSE)?

**MSE is one type of cost/loss function.**

Formula:

$$
MSE = \frac{1}{n}\sum_{i=1}^{n}(y_i-\hat{y}_i)^2
$$

Where:

- $y_i$ = Actual value
- $\hat{y}_i$ = Predicted value
- $n$ = Number of samples

### Example

Actual: `[10, 20]`

Predicted: `[12, 18]`

```text
Errors:
10 - 12 = -2
20 - 18 =  2

Squared errors:
(-2)² = 4
(2)²  = 4

MSE = (4 + 4) / 2
    = 4

## MAE (Mean Absolute Error)

MAE is another cost function, closely related to MSE but with one key difference: it uses absolute differences instead of squared differences.

$$MAE = \frac{1}{n}\sum_{i=1}^{n}|y_i - \hat{y}_i|$$

## MSE vs MAE — Core Differences

| | MSE | MAE |
|---|---|---|
| Formula | Squares the error | Takes absolute value of error |
| Sensitivity to outliers | High — big errors get squared, so they dominate | Low — treats all errors linearly |
| Gradient behavior | Smooth, differentiable everywhere; gradient scales with error size | Gradient is constant (±1) regardless of error size; not differentiable at 0 |
| Penalizes | Large errors much more heavily | All errors proportionally |
| Typical use case | When large errors are especially bad (and data doesn't have many outliers) | When you have outliers you don't want to dominate training, or want robustness |

## Why the Outlier Behavior Matters in Practice

- Predicted 10, actual 11 → error = 1 → MSE contributes 1, MAE contributes 1 (same)
- Predicted 10, actual 20 → error = 10 → MSE contributes 100, MAE contributes 10 (MSE punishes this way more)

MSE pushes your model harder to fix large errors, sometimes at the cost of many small errors elsewhere. MAE treats all mistakes "fairly," but the non-differentiability at zero can make gradient-based optimization trickier — often needs subgradient methods or smoothing tricks.

## Where Huber Loss Fits In

Huber Loss combines both: behaves like MSE for small errors (smooth gradient) and like MAE for large errors (robust to outliers). Useful when pure MSE is too outlier-sensitive but pure MAE is too unstable to train.

## MSLE (Mean Squared Logarithmic Error) - Mainly used when there is growth to find

MSLE applies a log transform to predictions and actual values before squaring the difference:

$$MSLE = \frac{1}{n}\sum_{i=1}^{n}(\log(y_i + 1) - \log(\hat{y}_i + 1))^2$$

The "+1" (sometimes written log1p) avoids taking log(0), which is undefined.

## Why the Log Transform Matters

- It penalizes **relative** (percentage) errors rather than **absolute** errors.
- Under-predictions and over-predictions of the same *ratio* are penalized similarly, unlike MSE where the actual magnitude of the difference dominates.
- Example: actual = 10, predicted = 20 (off by 10, ratio 2x) vs actual = 1000, predicted = 1010 (off by 10, ratio ~1x) — MSE treats both errors as equally bad (squared diff = 100 in both cases), but MSLE recognizes the first case is proportionally much worse.

## MSLE vs MSE

| | MSE | MSLE |
|---|---|---|
| Error type measured | Absolute difference | Relative / percentage difference |
| Sensitivity to large values | High — large absolute errors dominate | Reduced — large values are compressed by the log |
| Sensitivity to outliers | High | Lower, since log shrinks the scale of big numbers |
| Penalizes under vs over prediction | Symmetric | **Asymmetric** — penalizes under-prediction more heavily than over-prediction |
| Typical use case | General regression | Targets that grow exponentially or span several orders of magnitude (e.g. population, sales, counts) — where you care about relative error, not absolute error |

## Important Caveat: Requires Non-Negative Values

Since it takes a log, MSLE assumes \(y_i, \hat{y}_i \geq 0\). It breaks down (or needs modification) if your targets can be negative.

## The Asymmetry, Explained

For a fixed absolute gap, under-predicting is penalized more than over-predicting:

- Actual = 100, predicted = 50 (under by 50) → larger log-ratio penalty
- Actual = 100, predicted = 150 (over by 50) → smaller log-ratio penalty

This makes MSLE a natural fit when under-forecasting is more costly than over-forecasting (e.g. demand forecasting, where running out of stock is worse than having excess).